import React, { useState, useMemo } from "react";
import { Formik, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import { createPermission, updatePermission } from "./PermissionQueries";
import showToast from "../../../../helpers/ToastHelper";
import GlobalModal from "../../../../components/modal/GlobalModal";

export const PermissionFormModal = ({ show, selectedPermission, onSuccess, onClose }) => {
    const [loading, setLoading] = useState(false);
    const [autoGeneratedCodename, setAutoGeneratedCodename] = useState("");
    const [useAutoCodename, setUseAutoCodename] = useState(true);

    const generateCodename = (name) => {
        if (!name) return "";
        return name
            .toLowerCase()
            .trim()
            .replace(/\s+/g, "_")
            .replace(/[^a-z0-9_]/g, "")
            .replace(/^_+|_+$/g, "")
            .replace(/_+/g, "_");
    };

    const initialValues = useMemo(() => ({
        codename: selectedPermission?.codename || "",
        name: selectedPermission?.name || "",
        description: selectedPermission?.description || "",
        category: selectedPermission?.category || "",
    }), [selectedPermission]);

    const validationSchema = Yup.object().shape({
        codename: Yup.string()
            .min(3, "Code name must be at least 3 characters")
            .matches(/^[a-z_]+$/, "Code name can only contain lowercase letters and underscores"),
        name: Yup.string()
            .required("Permission name is required")
            .min(3, "Permission name must be at least 3 characters"),
        description: Yup.string(),
        category: Yup.string(),
    });

    const handleSubmit = async (values, { setErrors }) => {
        try {
            setLoading(true);

            const payload = {
                codename: useAutoCodename ? autoGeneratedCodename : values.codename.toLowerCase(),
                name: values.name,
                description: values.description,
                category: values.category,
            };

            if (selectedPermission) {
                const updatePayload = { ...payload };
                delete updatePayload.codename;
                await updatePermission(selectedPermission.id, updatePayload);
                showToast("success", "Permission updated successfully");
            } else {
                await createPermission(payload);
                showToast("success", "Permission created successfully");
            }

            if (onClose) onClose();
            if (onSuccess) onSuccess();
        } catch (error) {
            console.error("Permission submission error:", error);
            if (error.response && error.response.data) {
                setErrors(error.response.data);
                showToast("warning", "Validation failed");
            } else {
                showToast("error", "Something went wrong while saving the permission");
            }
        } finally {
            setLoading(false);
        }
    };

    const handleNameChange = (e, setFieldValue, values) => {
        const value = e.target.value;
        setFieldValue("name", value);
        if (!selectedPermission && useAutoCodename) {
            const generated = generateCodename(value);
            setAutoGeneratedCodename(generated);
        }
    };

    if (!show) return null;

    return (
        <GlobalModal
            show={show}
            onClose={onClose}
            title={<><i className="bx bx-lock me-2"></i>{selectedPermission ? "Edit Permission" : "Create New Permission"}</>}
            size="md"
            onSubmit={handleSubmit}
            submitText={selectedPermission ? "Update" : "Create"}
            loading={loading}
        >
            <Formik
                key={selectedPermission?.id || 'new'}
                initialValues={initialValues}
                validationSchema={validationSchema}
                onSubmit={handleSubmit}
            >
                {({ errors, values, setFieldValue }) => (
                    <>
                        {selectedPermission && (
                            <div className="alert alert-info mb-3">
                                <i className="bx bx-info-circle me-2"></i>
                                <strong>Code name cannot be changed</strong> - It serves as a unique identifier
                            </div>
                        )}

                        <div className="mb-3">
                            <label htmlFor="name" className="form-label">
                                Permission Name <span className="text-danger">*</span>
                            </label>
                            <Field
                                type="text"
                                className={`form-control ${errors.name ? "is-invalid" : ""}`}
                                id="name"
                                name="name"
                                placeholder="e.g., View Reports, Export Data"
                                onChange={(e) => handleNameChange(e, setFieldValue, values)}
                            />
                            <ErrorMessage name="name" component="div" className="text-danger small" />
                        </div>

                        <div className="mb-3">
                            <label htmlFor="codename" className="form-label">
                                Code Name <span className="text-danger">*</span>
                            </label>
                            {!selectedPermission && useAutoCodename ? (
                                <>
                                    <div className="input-group">
                                        <Field
                                            type="text"
                                            className={`form-control ${errors.codename ? "is-invalid" : ""}`}
                                            id="codename"
                                            name="codename"
                                            value={autoGeneratedCodename}
                                            placeholder="Auto-generated from permission name"
                                            disabled
                                        />
                                        <span className="input-group-text bg-light">
                                            <i className="bx bx-magic-wand text-primary"></i>
                                        </span>
                                    </div>
                                    <small className="text-muted d-block mt-1">
                                        Auto-generated from permission name. Can be customized by editing below.
                                    </small>
                                    {autoGeneratedCodename && (
                                        <button
                                            type="button"
                                            className="btn btn-link btn-sm p-0 mt-1"
                                            onClick={() => setUseAutoCodename(false)}
                                        >
                                            <i className="bx bx-pencil me-1"></i>
                                            Edit manually
                                        </button>
                                    )}
                                </>
                            ) : (
                                <>
                                    <Field
                                        type="text"
                                        className={`form-control ${errors.codename ? "is-invalid" : ""}`}
                                        id="codename"
                                        name="codename"
                                        placeholder="e.g., view_reports, export_data"
                                        disabled={selectedPermission ? true : false}
                                    />
                                    {!selectedPermission && (
                                        <button
                                            type="button"
                                            className="btn btn-link btn-sm p-0 mt-1"
                                            onClick={() => {
                                                const generated = generateCodename(values.name);
                                                setAutoGeneratedCodename(generated);
                                                setUseAutoCodename(true);
                                            }}
                                        >
                                            <i className="bx bx-reset me-1"></i>
                                            Use auto-generated
                                        </button>
                                    )}
                                </>
                            )}
                            <ErrorMessage name="codename" component="div" className="text-danger small" />
                            <small className="text-muted d-block mt-1">
                                Lowercase letters and underscores only. Used as unique identifier.
                            </small>
                        </div>

                        <div className="mb-3">
                            <label htmlFor="category" className="form-label">
                                Category
                            </label>
                            <Field
                                type="text"
                                className="form-control"
                                id="category"
                                name="category"
                                placeholder="e.g., Reports, Data Management"
                            />
                            <small className="text-muted d-block mt-1">Group permissions by category</small>
                        </div>

                        <div className="mb-3">
                            <label htmlFor="description" className="form-label">
                                Description
                            </label>
                            <Field
                                as="textarea"
                                className="form-control"
                                id="description"
                                name="description"
                                rows="3"
                                placeholder="Describe what this permission allows..."
                            />
                        </div>
                    </>
                )}
            </Formik>
        </GlobalModal>
    );
};
