import React, { useState, useEffect } from "react";
import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import { createPermission, updatePermission } from "./PermissionQueries";
import showToast from "../../../../helpers/ToastHelper";

export const PermissionFormModal = ({ selectedPermission, onSuccess, onClose }) => {
    const [initialValues, setInitialValues] = useState({
        codename: "",
        name: "",
        description: "",
        category: "",
    });
    const [autoGeneratedCodename, setAutoGeneratedCodename] = useState("");
    const [useAutoCodename, setUseAutoCodename] = useState(true);

    // Function to generate codename from name
    const generateCodename = (name) => {
        if (!name) return "";
        return name
            .toLowerCase()
            .trim()
            .replace(/\s+/g, "_") // Replace spaces with underscores
            .replace(/[^a-z0-9_]/g, "") // Remove special characters
            .replace(/^_+|_+$/g, "") // Remove leading/trailing underscores
            .replace(/_+/g, "_"); // Replace multiple underscores with single
    };

    const validationSchema = Yup.object().shape({
        codename: Yup.string()
            .min(3, "Code name must be at least 3 characters")
            .matches(/^[a-z_]+$/, "Code name can only contain lowercase letters and underscores"),
        name: Yup.string()
            .required("Permission name is required")
            .min(3, "Permission name must be at least 3 characters"),
        description: Yup.string(),
        category: Yup.string(),
    });

    const validate = (values) => {
        const errors = {};
        
        // Validate name
        if (!values.name || values.name.trim().length === 0) {
            errors.name = "Permission name is required";
        } else if (values.name.length < 3) {
            errors.name = "Permission name must be at least 3 characters";
        }
        
        // Validate codename - only if not using auto-generation or manually editing
        if (!useAutoCodename || values.codename) {
            if (!values.codename || values.codename.trim().length === 0) {
                errors.codename = "Code name is required";
            } else if (values.codename.length < 3) {
                errors.codename = "Code name must be at least 3 characters";
            } else if (!/^[a-z_]+$/.test(values.codename)) {
                errors.codename = "Code name can only contain lowercase letters and underscores";
            }
        } else if (useAutoCodename && !autoGeneratedCodename) {
            // If using auto-generation, make sure it generated a valid code
            errors.codename = "Please enter a permission name to generate code name";
        }
        
        return errors;
    };

    useEffect(() => {
        if (selectedPermission) {
            setInitialValues({
                codename: selectedPermission.codename || "",
                name: selectedPermission.name || "",
                description: selectedPermission.description || "",
                category: selectedPermission.category || "",
            });
            setUseAutoCodename(false);
        } else {
            setInitialValues({
                codename: "",
                name: "",
                description: "",
                category: "",
            });
            setUseAutoCodename(true);
        }
    }, [selectedPermission]);

    const handleSubmit = async (values, { setSubmitting, resetForm, setErrors }) => {
        try {
            setSubmitting(true);

            const payload = {
                codename: useAutoCodename ? autoGeneratedCodename : values.codename.toLowerCase(),
                name: values.name,
                description: values.description,
                category: values.category,
            };

            if (selectedPermission) {
                // Remove codename from update payload (read-only)
                const updatePayload = { ...payload };
                delete updatePayload.codename;
                await updatePermission(selectedPermission.id, updatePayload);
                showToast("success", "Permission updated successfully");
            } else {
                await createPermission(payload);
                showToast("success", "Permission created successfully");
            }

            handleClose();
            resetForm();
            if (onSuccess) onSuccess();
        } catch (error) {
            console.error("Permission submission error:", error);
            if (error.response && error.response.data) {
                setErrors(error.response.data);
                showToast("warning", "Validation failed");
            } else {
                showToast("error", "Something went wrong while saving the permission");
            }
        } finally {
            setSubmitting(false);
        }
    };

    const handleClose = () => {
        if (onClose) onClose();
    };

    return (
        <div
            className="modal fade show d-block"
            tabIndex="-1"
            style={{ backgroundColor: "rgba(0, 0, 0, 0.5)" }}
            aria-hidden="false"
        >
            <div className="modal-dialog" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <h5 className="modal-title">
                            <i className="bx bx-lock me-2"></i>
                            {selectedPermission ? "Edit Permission" : "Create New Permission"}
                        </h5>
                        <button
                            type="button"
                            className="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"
                            onClick={handleClose}
                        ></button>
                    </div>

                    <Formik
                        enableReinitialize
                        initialValues={initialValues}
                        validate={validate}
                        onSubmit={handleSubmit}
                    >
                        {({ isSubmitting, errors, touched, values, setFieldValue }) => (
                            <Form>
                                <div className="modal-body">
                                    {selectedPermission && (
                                        <div className="alert alert-info mb-3">
                                            <i className="bx bx-info-circle me-2"></i>
                                            <strong>Code name cannot be changed</strong> - It serves as a unique identifier
                                        </div>
                                    )}

                                                    <div className="mb-3">
                                                         <label htmlFor="name" className="form-label">
                                                             Permission Name <span className="text-danger">*</span>
                                                         </label>
                                                         <Field
                                                             type="text"
                                                             className={`form-control ${
                                                                 errors.name && touched.name ? "is-invalid" : ""
                                                             }`}
                                                             id="name"
                                                             name="name"
                                                             placeholder="e.g., View Reports, Export Data"
                                                             onChange={(e) => {
                                                                 const { value } = e.target;
                                                                 // Update Formik field value
                                                                 setFieldValue("name", value);
                                                                 // Auto-generate codename for create mode
                                                                 if (!selectedPermission && useAutoCodename) {
                                                                     const generated = generateCodename(value);
                                                                     setAutoGeneratedCodename(generated);
                                                                 }
                                                             }}
                                                         />
                                                         <ErrorMessage name="name" component="div" className="invalid-feedback" />
                                                     </div>

                                                    <div className="mb-3">
                                                        <label htmlFor="codename" className="form-label">
                                                            Code Name <span className="text-danger">*</span>
                                                        </label>
                                                        {!selectedPermission && useAutoCodename ? (
                                                            <>
                                                                <div className="input-group">
                                                                    <input
                                                                        type="text"
                                                                        className={`form-control ${
                                                                            errors.codename && touched.codename ? "is-invalid" : ""
                                                                        }`}
                                                                        id="codename"
                                                                        name="codename"
                                                                        value={autoGeneratedCodename}
                                                                        placeholder="Auto-generated from permission name"
                                                                        disabled
                                                                    />
                                                                    <span className="input-group-text bg-light">
                                                                        <i className="bx bx-magic-wand text-primary"></i>
                                                                    </span>
                                                                </div>
                                                                <small className="text-muted d-block mt-1">
                                                                    Auto-generated from permission name. Can be customized by editing below.
                                                                </small>
                                                                {autoGeneratedCodename && (
                                                                    <button
                                                                        type="button"
                                                                        className="btn btn-link btn-sm mt-2 p-0"
                                                                        onClick={() => setUseAutoCodename(false)}
                                                                    >
                                                                        <i className="bx bx-pencil me-1"></i>
                                                                        Edit manually
                                                                    </button>
                                                                )}
                                                            </>
                                                        ) : (
                                                            <>
                                                                <Field
                                                                    type="text"
                                                                    className={`form-control ${
                                                                        errors.codename && touched.codename ? "is-invalid" : ""
                                                                    }`}
                                                                    id="codename"
                                                                    name="codename"
                                                                    placeholder="e.g., view_reports, export_data"
                                                                    disabled={selectedPermission ? true : false}
                                                                />
                                                                {!selectedPermission && (
                                                                    <button
                                                                        type="button"
                                                                        className="btn btn-link btn-sm mt-2 p-0"
                                                                        onClick={() => {
                                                                            const name = values.name;
                                                                            const generated = generateCodename(name);
                                                                            setAutoGeneratedCodename(generated);
                                                                            setUseAutoCodename(true);
                                                                        }}
                                                                    >
                                                                        <i className="bx bx-reset me-1"></i>
                                                                        Use auto-generated
                                                                    </button>
                                                                )}
                                                            </>
                                                        )}
                                                        <ErrorMessage name="codename" component="div" className="invalid-feedback" />
                                                        <small className="text-muted d-block mt-1">
                                                            Lowercase letters and underscores only. Used as unique identifier.
                                                        </small>
                                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="category" className="form-label">
                                            Category
                                        </label>
                                        <Field
                                            type="text"
                                            className={`form-control ${
                                                errors.category && touched.category ? "is-invalid" : ""
                                            }`}
                                            id="category"
                                            name="category"
                                            placeholder="e.g., Reports, Data Management"
                                        />
                                        <ErrorMessage name="category" component="div" className="invalid-feedback" />
                                        <small className="text-muted d-block mt-1">Group permissions by category</small>
                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="description" className="form-label">
                                            Description
                                        </label>
                                        <Field
                                            as="textarea"
                                            className={`form-control ${
                                                errors.description && touched.description ? "is-invalid" : ""
                                            }`}
                                            id="description"
                                            name="description"
                                            rows="3"
                                            placeholder="Describe what this permission allows..."
                                        />
                                        <ErrorMessage name="description" component="div" className="invalid-feedback" />
                                    </div>
                                </div>

                                <div className="modal-footer">
                                    <button
                                        type="button"
                                        className="btn btn-outline-secondary"
                                        data-bs-dismiss="modal"
                                        onClick={handleClose}
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        className="btn btn-primary"
                                        disabled={isSubmitting}
                                    >
                                        {isSubmitting ? (
                                            <>
                                                <span
                                                    className="spinner-border spinner-border-sm me-1"
                                                    role="status"
                                                    aria-hidden="true"
                                                ></span>
                                                Saving...
                                            </>
                                        ) : selectedPermission ? (
                                            "Update Permission"
                                        ) : (
                                            "Create Permission"
                                        )}
                                    </button>
                                </div>
                            </Form>
                        )}
                    </Formik>
                </div>
            </div>
        </div>
    );
};
